language: python
python:
  - 3.3
  - 3.4
  - pypy3
install:
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - pip install mock
  - pip install nose
  - pip install requests
  - pip install responses
script:
  - nosetests tests --with-coverage --cover-package=retdec --cover-erase
  - flake8 --ignore=E501 retdec tests
after_success:
  - coveralls
